"""Framework-neutral contracts and state semantics for CUC harness orchestration."""

from .contracts import (
    ChangeSet,
    EvalResult,
    FindingSeverity,
    GateOutcome,
    PlanArtifact,
    ResearchArtifact,
    ReviewDisposition,
    ReviewFinding,
    ReviewResult,
    RunPhase,
    RunState,
    TaskSpec,
    TestIntent,
    TestKind,
    TestResult,
)
from .state_machine import (
    ChangeRecorded,
    EvalRecorded,
    InvalidTransition,
    PlanRecorded,
    ResearchRecorded,
    ResumeRequested,
    ReviewRecorded,
    TestRecorded,
    TestsDeclared,
    VerificationPassed,
    apply_event,
)

__all__ = [
    "ChangeRecorded",
    "ChangeSet",
    "EvalRecorded",
    "EvalResult",
    "FindingSeverity",
    "GateOutcome",
    "InvalidTransition",
    "PlanArtifact",
    "PlanRecorded",
    "ResearchArtifact",
    "ResearchRecorded",
    "ResumeRequested",
    "ReviewDisposition",
    "ReviewFinding",
    "ReviewRecorded",
    "ReviewResult",
    "RunPhase",
    "RunState",
    "TaskSpec",
    "TestIntent",
    "TestKind",
    "TestRecorded",
    "TestResult",
    "TestsDeclared",
    "VerificationPassed",
    "apply_event",
]
