"""HARN-028 column loader: one complete column from repository data into HARN-018 state.

The work unit is the whole column, every token in textual order. The loader reads
the pinned automatic parsing file (7 columns) and the already-seeded reviewed file
(8 columns), requires their target-column token sequences to agree, and binds the
task to the canonical ``review-automatic-parsing`` capability so completion gates
come from the manifest. It performs no writes.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Mapping

from .column_state import ColumnSnapshot, ColumnTask, ColumnToken
from .langgraph_column_review import build_column_task_from_capability
from .skill_capabilities import SkillCapabilityRegistry

AUTO_HEADER = ("id", "surface form", "morphological parsing", "DULAT", "POS", "gloss", "comments")
REVIEWED_HEADER = (
    "id", "surface form", "sign span", "morphological parsing", "DULAT", "POS", "gloss", "comments",
)
COLUMNLESS = "-"

# ``# KTU 1.6 I:2`` (columned) and ``# KTU 2.10 4`` (columnless letter).
_LINE_MARKER_RE = re.compile(r"^# (KTU \S+)(?: ([IVX]+):| )(\d+)$")
_TABLET_RE = re.compile(r"^KTU \S+$")


def _required_text(value: object, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field} must be a non-empty string")
    return value.strip()


@dataclass(frozen=True)
class AutomaticRow:
    """One automatic-parsing alternative for a token, as generated by the pipeline."""

    morphological_parsing: str
    dulat: str
    pos: str
    gloss: str
    comments: str

    def to_dict(self) -> dict[str, str]:
        return {
            "morphological_parsing": self.morphological_parsing,
            "dulat": self.dulat,
            "pos": self.pos,
            "gloss": self.gloss,
            "comments": self.comments,
        }


@dataclass(frozen=True)
class _ColumnRow:
    token_id: str
    line_ref: str
    fields: tuple[str, ...]
    line_number: int


@dataclass(frozen=True)
class LoadedColumn:
    task: ColumnTask
    snapshot: ColumnSnapshot
    automatic_rows: Mapping[str, tuple[AutomaticRow, ...]]
    reviewed_text: str
    auto_sha256: str
    reviewed_sha256: str
    tf_version: str
    auto_relative_path: str
    reviewed_relative_path: str
    repo_root: str
    capability_root: str

    def __post_init__(self) -> None:
        if not isinstance(self.task, ColumnTask) or not isinstance(self.snapshot, ColumnSnapshot):
            raise ValueError("LoadedColumn requires ColumnTask and ColumnSnapshot")
        rows = {
            key: tuple(value) for key, value in dict(self.automatic_rows).items()
        }
        if tuple(rows) != self.snapshot.token_ids:
            raise ValueError("automatic rows must cover exactly the snapshot tokens in order")
        if any(not value for value in rows.values()):
            raise ValueError("every snapshot token needs at least one automatic row")
        object.__setattr__(self, "automatic_rows", rows)


def _read_column_rows(
    text: str,
    *,
    tablet: str,
    column: str,
    header: tuple[str, ...],
    label: str,
) -> tuple[_ColumnRow, ...]:
    """Return every data row that sits under a marker of the target column, in order."""

    lines = text.splitlines()
    if not lines or tuple(lines[0].split("\t")) != header:
        raise ValueError(
            f"{label} must use the canonical {len(header)}-column header: "
            + "\t".join(header).replace("\t", " | ")
        )
    rows: list[_ColumnRow] = []
    current_tablet: str | None = None
    current_column: str | None = None
    current_line: str | None = None
    for index, raw in enumerate(lines[1:], start=2):
        if raw.startswith("#"):
            marker = _LINE_MARKER_RE.match(raw.rstrip("\t"))
            if marker is None:
                current_tablet = current_column = current_line = None
                continue
            current_tablet = marker.group(1)
            current_column = marker.group(2) or COLUMNLESS
            current_line = marker.group(3)
            continue
        if current_tablet != tablet or current_column != column:
            continue
        fields = tuple(raw.split("\t"))
        token_id = fields[0].strip()
        if not token_id.isdigit():
            continue
        line_ref = current_line if column == COLUMNLESS else f"{column}:{current_line}"
        rows.append(_ColumnRow(token_id, line_ref, fields, index))
    return tuple(rows)


def _group_in_order(rows: tuple[_ColumnRow, ...]) -> dict[str, list[_ColumnRow]]:
    grouped: dict[str, list[_ColumnRow]] = {}
    for row in rows:
        grouped.setdefault(row.token_id, []).append(row)
    return grouped


def load_column(
    repo_root: Path | str,
    *,
    tablet: str,
    column: str,
    tf_version: str,
    repository_revision: str,
    task_id: str,
    evidence_priority_token_ids: tuple[str, ...] = (),
    capability_root: Path | str | None = None,
    corpus: str = "CUC",
) -> LoadedColumn:
    root = Path(repo_root).resolve()
    tablet = _required_text(tablet, "tablet")
    if not _TABLET_RE.fullmatch(tablet):
        raise ValueError("tablet must look like 'KTU 1.6'")
    column = _required_text(column, "column")
    if column != COLUMNLESS and not re.fullmatch(r"[IVX]+", column):
        raise ValueError(f"column must be a roman numeral or '-' for columnless tablets, not {column!r}")
    tf_version = _required_text(tf_version, "tf_version")

    auto_relative = f"auto_parsing/{tf_version}/{tablet}.tsv"
    reviewed_relative = f"reviewed/{tablet}.tsv"
    auto_path = root / auto_relative
    reviewed_path = root / reviewed_relative
    if not auto_path.is_file():
        raise ValueError(f"automatic parsing file not found for TF {tf_version}: {auto_relative}")
    if not reviewed_path.is_file():
        raise ValueError(f"reviewed file not found (seed it first): {reviewed_relative}")

    auto_bytes = auto_path.read_bytes()
    reviewed_bytes = reviewed_path.read_bytes()
    auto_text = auto_bytes.decode("utf-8")
    reviewed_text = reviewed_bytes.decode("utf-8")

    auto_rows = _read_column_rows(
        auto_text, tablet=tablet, column=column, header=AUTO_HEADER, label=auto_relative
    )
    reviewed_rows = _read_column_rows(
        reviewed_text, tablet=tablet, column=column, header=REVIEWED_HEADER, label=reviewed_relative
    )
    if not auto_rows:
        raise ValueError(f"column {column} of {tablet} has no tokens in {auto_relative}")
    if not reviewed_rows:
        raise ValueError(
            f"column {column} of {tablet} has no tokens in {reviewed_relative}; "
            "seed it with seed_reviewed_column_range.py first"
        )

    auto_grouped = _group_in_order(auto_rows)
    reviewed_grouped = _group_in_order(reviewed_rows)
    auto_ids = tuple(auto_grouped)
    reviewed_ids = tuple(reviewed_grouped)
    missing_in_reviewed = [tid for tid in auto_ids if tid not in reviewed_grouped]
    missing_in_auto = [tid for tid in reviewed_ids if tid not in auto_grouped]
    if missing_in_reviewed:
        raise ValueError(
            f"tokens present in {auto_relative} but missing from the seeded reviewed column: "
            + ", ".join(missing_in_reviewed)
        )
    if missing_in_auto:
        raise ValueError(
            f"tokens present in {reviewed_relative} but missing from the automatic column: "
            + ", ".join(missing_in_auto)
        )
    if auto_ids != reviewed_ids:
        raise ValueError(
            "reviewed token order differs from the automatic token sequence for "
            f"{tablet} {column}: reviewed={reviewed_ids!r} automatic={auto_ids!r}"
        )

    tokens: list[ColumnToken] = []
    automatic: dict[str, tuple[AutomaticRow, ...]] = {}
    for ordinal, token_id in enumerate(auto_ids, start=1):
        auto_group = auto_grouped[token_id]
        reviewed_group = reviewed_grouped[token_id]
        for row in auto_group:
            if len(row.fields) != len(AUTO_HEADER):
                raise ValueError(
                    f"malformed automatic row for token {token_id} at line {row.line_number}: "
                    f"expected {len(AUTO_HEADER)} columns"
                )
        for row in reviewed_group:
            if len(row.fields) != len(REVIEWED_HEADER):
                raise ValueError(
                    f"malformed reviewed row for token {token_id} at line {row.line_number}: "
                    f"expected 8 columns"
                )
            if not row.fields[2].strip():
                raise ValueError(
                    f"reviewed row for token {token_id} at line {row.line_number} has no sign span"
                )
        auto_surface = auto_group[0].fields[1]
        reviewed_surface = reviewed_group[0].fields[1]
        if auto_surface != reviewed_surface:
            raise ValueError(
                f"surface mismatch for token {token_id}: automatic {auto_surface!r} "
                f"vs reviewed {reviewed_surface!r}"
            )
        if any(row.fields[1] != auto_surface for row in auto_group + reviewed_group):
            raise ValueError(f"surface differs across alternative rows of token {token_id}")
        line_refs = {row.line_ref for row in auto_group} | {row.line_ref for row in reviewed_group}
        if len(line_refs) != 1:
            raise ValueError(f"token {token_id} is not bound to exactly one line: {sorted(line_refs)}")
        tokens.append(ColumnToken(token_id, ordinal, auto_group[0].line_ref, auto_surface))
        automatic[token_id] = tuple(
            AutomaticRow(row.fields[2], row.fields[3], row.fields[4], row.fields[5], row.fields[6])
            for row in auto_group
        )

    auto_digest = sha256(auto_bytes).hexdigest()
    reviewed_digest = sha256(reviewed_bytes).hexdigest()
    snapshot_identity = json.dumps(
        {
            "tf_version": tf_version,
            "tablet": tablet,
            "column": column,
            "tokens": [[t.token_id, t.line_ref, t.surface] for t in tokens],
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    snapshot = ColumnSnapshot(
        snapshot_id="snapshot-" + sha256(snapshot_identity.encode("utf-8")).hexdigest()[:24],
        source_ref=f"{auto_relative}#{column}",
        source_provenance=json.dumps(
            {
                "tf_version": tf_version,
                "auto_path": auto_relative,
                "auto_sha256": auto_digest,
                "reviewed_path": reviewed_relative,
                "reviewed_sha256": reviewed_digest,
            },
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ),
        tokens=tuple(tokens),
    )

    registry = SkillCapabilityRegistry(Path(capability_root or root))
    manifest = registry.get("review-automatic-parsing")
    provenance = registry.provenance("review-automatic-parsing")
    task = build_column_task_from_capability(
        manifest,
        provenance,
        task_id=task_id,
        corpus=corpus,
        tablet=tablet,
        column=column,
        repository_revision=repository_revision,
        evidence_priority_token_ids=tuple(evidence_priority_token_ids),
    )
    return LoadedColumn(
        task=task,
        snapshot=snapshot,
        automatic_rows=automatic,
        reviewed_text=reviewed_text,
        auto_sha256=auto_digest,
        reviewed_sha256=reviewed_digest,
        tf_version=tf_version,
        auto_relative_path=auto_relative,
        reviewed_relative_path=reviewed_relative,
        repo_root=str(root),
        capability_root=str(registry.repo_root),
    )
